const router=require("express").Router(),fs=require("fs"),path=require("path"),crypto=require("crypto"),archiver=require("archiver"),multer=require("multer"),sharp=require("sharp");
const auth=require("../middleware/auth"),admin=require("../middleware/admin"),{safeName,ext,sha256,ensureDir,randomToken}=require("../utils/helpers"),storage=require("../services/storage"),audit=require("../services/audit");
const User=require("../models/User"),File=require("../models/File"),Folder=require("../models/Folder"),Share=require("../models/Share"),Comment=require("../models/Comment"),Version=require("../models/FileVersion"),Upload=require("../models/UploadSession"),Notification=require("../models/Notification"),Activity=require("../models/ActivityLog");
router.use(auth);
const upload=multer({dest:path.join(storage.root,"temporary"),limits:{fileSize:Number(process.env.MAX_FILE_SIZE)||524288000}});
const ok=(res,data,message="OK")=>res.json({success:true,message,data});
router.get("/users/me",(req,res)=>ok(res,{user:{id:req.user._id,name:req.user.name,email:req.user.email,role:req.user.role,quota:req.user.quota,usedStorage:req.user.usedStorage,profilePhoto:req.user.profilePhoto,createdAt:req.user.createdAt}}));
router.patch("/users/me",async(req,res,next)=>{try{req.user.name=String(req.body.name||req.user.name).slice(0,100);await req.user.save();ok(res,{user:req.user},"Profile updated")}catch(e){next(e)}});
router.get("/files",async(req,res,next)=>{try{const folder=req.query.folder||null;const q={owner:req.user._id,folder,trashed:false};if(req.query.starred==="true")q.starred=true;const files=await File.find(q).sort({updatedAt:-1}).lean();const folders=await Folder.find({owner:req.user._id,parent:folder,trashed:false}).sort({name:1}).lean();ok(res,{files,folders});}catch(e){next(e)}});
router.post("/files/upload",upload.array("files",50),async(req,res,next)=>{try{
 const folder=req.body.folder||null;const out=[];for(const f of req.files){if(req.user.usedStorage+f.size>req.user.quota){fs.unlinkSync(f.path);continue}
  const name=safeName(f.originalname), target=storage.filePath(req.user._id,crypto.randomUUID()+"-"+name);ensureDir(path.dirname(target));fs.renameSync(f.path,target);
  const hash=await sha256(target);let duplicate=await File.findOne({owner:req.user._id,hash,trashed:false});if(duplicate){fs.unlinkSync(target);out.push({duplicate:true,file:duplicate});continue}
  let thumb="";if(f.mimetype.startsWith("image/")){thumb=path.join(storage.userDir(req.user._id),"thumb-"+path.basename(target)+".webp");try{await sharp(target).resize(360,360,{fit:"inside"}).webp({quality:78}).toFile(thumb)}catch{}}
  const file=await File.create({name,originalName:f.originalname,extension:ext(name),mimeType:f.mimetype,size:f.size,hash,owner:req.user._id,folder,storagePath:target,thumbnailPath:thumb});
  req.user.usedStorage+=f.size;out.push({file});await audit(req,"upload",{file:file._id});
 }
 await req.user.save();req.app.get("io").to("user:"+req.user._id).emit("storage-update");ok(res,{files:out},"Upload complete");
}catch(e){next(e)}});
router.post("/folders",async(req,res,next)=>{try{const f=await Folder.create({name:safeName(req.body.name||"New folder"),owner:req.user._id,parent:req.body.parent||null});await audit(req,"create-folder",{folder:f._id});ok(res,{folder:f},"Folder created")}catch(e){next(e)}});
router.patch("/folders/:id",async(req,res,next)=>{try{const f=await Folder.findOne({_id:req.params.id,owner:req.user._id});if(!f)return res.status(404).json({success:false,message:"Folder not found"});if(req.body.name)f.name=safeName(req.body.name);if("parent"in req.body)f.parent=req.body.parent||null;if("starred"in req.body)f.starred=!!req.body.starred;await f.save();ok(res,{folder:f},"Folder updated")}catch(e){next(e)}});
router.delete("/folders/:id",async(req,res,next)=>{try{const f=await Folder.findOne({_id:req.params.id,owner:req.user._id});if(!f)return res.status(404).json({success:false,message:"Folder not found"});f.trashed=true;f.trashedAt=new Date();await f.save();await File.updateMany({owner:req.user._id,folder:f._id},{trashed:true,trashedAt:new Date()});ok(res,null,"Moved to trash")}catch(e){next(e)}});
router.patch("/files/:id",async(req,res,next)=>{try{const f=await File.findOne({_id:req.params.id,owner:req.user._id,trashed:false});if(!f)return res.status(404).json({success:false,message:"File not found"});if(req.body.name)f.name=safeName(req.body.name);if("folder"in req.body)f.folder=req.body.folder||null;if("starred"in req.body)f.starred=!!req.body.starred;f.updatedAt=new Date();await f.save();await audit(req,"update-file",{file:f._id});ok(res,{file:f},"File updated")}catch(e){next(e)}});
router.delete("/files/:id",async(req,res,next)=>{try{const f=await File.findOne({_id:req.params.id,owner:req.user._id,trashed:false});if(!f)return res.status(404).json({success:false,message:"File not found"});f.trashed=true;f.trashedAt=new Date();await f.save();req.user.usedStorage=Math.max(0,req.user.usedStorage-f.size);await req.user.save();await audit(req,"delete",{file:f._id});ok(res,null,"Moved to trash")}catch(e){next(e)}});
router.get("/files/:id/preview",async(req,res,next)=>{try{const f=await File.findOne({_id:req.params.id,owner:req.user._id,trashed:false});if(!f||!storage.publicSafe(f.storagePath)||!fs.existsSync(f.storagePath))return res.status(404).json({success:false,message:"File not found"});f.lastAccessed=new Date();await f.save();res.type(f.mimeType||"application/octet-stream");fs.createReadStream(f.storagePath).pipe(res);}catch(e){next(e)}});
router.get("/files/:id/download",async(req,res,next)=>{try{const f=await File.findOne({_id:req.params.id,owner:req.user._id,trashed:false});if(!f)return res.status(404).json({success:false,message:"File not found"});await audit(req,"download",{file:f._id});res.download(f.storagePath,f.name)}catch(e){next(e)}});
router.post("/files/:id/copy",async(req,res,next)=>{try{const f=await File.findOne({_id:req.params.id,owner:req.user._id,trashed:false});if(!f)return res.status(404).json({success:false,message:"File not found"});if(req.user.usedStorage+f.size>req.user.quota)return res.status(413).json({success:false,message:"Storage quota exceeded"});const target=storage.filePath(req.user._id,crypto.randomUUID()+"-"+safeName(f.name));fs.copyFileSync(f.storagePath,target);const n=await File.create({...f.toObject(),_id:undefined,name:"Copy of "+f.name,storagePath:target,folder:req.body.folder||f.folder,createdAt:new Date(),updatedAt:new Date(),isNew:undefined});req.user.usedStorage+=f.size;await req.user.save();ok(res,{file:n},"File copied")}catch(e){next(e)}});
router.get("/search",async(req,res,next)=>{try{const q=String(req.query.q||"").trim();const filter={owner:req.user._id,trashed:false};if(q)filter.$or=[{name:{$regex:q,$options:"i"}},{originalName:{$regex:q,$options:"i"}}];if(req.query.type)filter.mimeType={$regex:"^"+String(req.query.type).replace(/[.*+?^${}()|[\]\\]/g,"\\$&"),$options:"i"};const files=await File.find(filter).sort({updatedAt:-1}).limit(200).lean();ok(res,{files});}catch(e){next(e)}});
router.get("/trash",async(req,res,next)=>{try{const [files,folders]=await Promise.all([File.find({owner:req.user._id,trashed:true}).sort({trashedAt:-1}),Folder.find({owner:req.user._id,trashed:true}).sort({trashedAt:-1})]);ok(res,{files,folders});}catch(e){next(e)}});
router.post("/trash/restore",async(req,res,next)=>{try{for(const id of req.body.fileIds||[])await File.updateOne({_id:id,owner:req.user._id,trashed:true},{trashed:false,trashedAt:null});for(const id of req.body.folderIds||[])await Folder.updateOne({_id:id,owner:req.user._id,trashed:true},{trashed:false,trashedAt:null});const files=await File.find({owner:req.user._id,trashed:false});req.user.usedStorage=files.reduce((s,f)=>s+f.size,0);await req.user.save();ok(res,null,"Restored")}catch(e){next(e)}});
router.delete("/trash/empty",async(req,res,next)=>{try{const fsx=await File.find({owner:req.user._id,trashed:true});for(const f of fsx){try{if(f.storagePath)fs.unlinkSync(f.storagePath);if(f.thumbnailPath)fs.unlinkSync(f.thumbnailPath)}catch{}await f.deleteOne()}await Folder.deleteMany({owner:req.user._id,trashed:true});ok(res,null,"Trash emptied")}catch(e){next(e)}});
router.post("/files/:id/share",async(req,res,next)=>{try{const f=await File.findOne({_id:req.params.id,owner:req.user._id,trashed:false});if(!f)return res.status(404).json({success:false,message:"File not found"});const s=await Share.create({token:randomToken(),file:f._id,owner:req.user._id,permission:req.body.permission||"viewer",publicLink:req.body.publicLink!==false,allowDownload:req.body.allowDownload!==false,expiresAt:req.body.expiresAt?new Date(req.body.expiresAt):undefined});const link=`${req.protocol}://${req.get("host")}/share/${s.token}`;ok(res,{share:s,link},"Share link created")}catch(e){next(e)}});
router.get("/files/:id/comments",async(req,res,next)=>{try{const f=await File.findOne({_id:req.params.id,owner:req.user._id});if(!f)return res.status(404).json({success:false,message:"File not found"});ok(res,{comments:await Comment.find({file:f._id}).populate("user","name email").sort({createdAt:1})});}catch(e){next(e)}});
router.post("/files/:id/comments",async(req,res,next)=>{try{const f=await File.findOne({_id:req.params.id,owner:req.user._id});if(!f)return res.status(404).json({success:false,message:"File not found"});const c=await Comment.create({file:f._id,user:req.user._id,text:String(req.body.text||"").slice(0,5000)});ok(res,{comment:c},"Comment added")}catch(e){next(e)}});
router.get("/files/:id/versions",async(req,res,next)=>{try{const f=await File.findOne({_id:req.params.id,owner:req.user._id});if(!f)return res.status(404).json({success:false,message:"File not found"});ok(res,{versions:await Version.find({file:f._id}).sort({version:-1})});}catch(e){next(e)}});
router.get("/notifications",async(req,res,next)=>{try{ok(res,{notifications:await Notification.find({user:req.user._id}).sort({createdAt:-1}).limit(100)})}catch(e){next(e)}});
router.patch("/notifications/:id/read",async(req,res,next)=>{try{await Notification.updateOne({_id:req.params.id,user:req.user._id},{read:true});ok(res,null,"Marked read")}catch(e){next(e)}});
router.get("/activity",async(req,res,next)=>{try{ok(res,{activity:await Activity.find({user:req.user._id}).populate("file","name").sort({timestamp:-1}).limit(200)})}catch(e){next(e)}});
router.get("/storage",async(req,res,next)=>{try{const files=await File.find({owner:req.user._id,trashed:false}).lean();const by={};for(const f of files){const k=(f.mimeType||"other").split("/")[0];by[k]=(by[k]||0)+f.size}ok(res,{quota:req.user.quota,used:req.user.usedStorage,available:Math.max(0,req.user.quota-req.user.usedStorage),percentage:req.user.quota?Math.round(req.user.usedStorage/req.user.quota*100):0,types:by,largest:[...files].sort((a,b)=>b.size-a.size).slice(0,10)})}catch(e){next(e)}});
router.post("/uploads/session",async(req,res,next)=>{try{const size=Number(req.body.size);if(!size||size<1)return res.status(400).json({success:false,message:"Invalid size"});if(req.user.usedStorage+size>req.user.quota)return res.status(413).json({success:false,message:"Storage quota exceeded"});const id=crypto.randomUUID(),dir=path.join(storage.root,"temporary",id);ensureDir(dir);const s=await Upload.create({user:req.user._id,fileName:safeName(req.body.fileName),mimeType:req.body.mimeType,size,folder:req.body.folder||null,totalChunks:Number(req.body.totalChunks),tempDir:dir,hash:req.body.hash||""});ok(res,{uploadId:s._id,totalChunks:s.totalChunks})}catch(e){next(e)}});
router.put("/uploads/:id/chunk/:index",async(req,res,next)=>{try{const s=await Upload.findOne({_id:req.params.id,user:req.user._id,status:"uploading"});if(!s)return res.status(404).json({success:false,message:"Upload session not found"});const idx=Number(req.params.index);const out=path.join(s.tempDir,String(idx));const ws=fs.createWriteStream(out);req.pipe(ws);ws.on("finish",async()=>{if(!s.receivedChunks.includes(idx))s.receivedChunks.push(idx);await s.save();ok(res,{received:idx})});ws.on("error",next)}catch(e){next(e)}});
router.post("/uploads/:id/complete",async(req,res,next)=>{try{const s=await Upload.findOne({_id:req.params.id,user:req.user._id,status:"uploading"});if(!s)return res.status(404).json({success:false,message:"Upload session not found"});if(s.receivedChunks.length!==s.totalChunks)return res.status(400).json({success:false,message:"Missing chunks"});const target=storage.filePath(req.user._id,crypto.randomUUID()+"-"+s.fileName);ensureDir(path.dirname(target));const ws=fs.createWriteStream(target);for(let i=0;i<s.totalChunks;i++)ws.write(fs.readFileSync(path.join(s.tempDir,String(i))));ws.end();await new Promise(r=>ws.on("close",r));const actual=await sha256(target);if(s.hash&&s.hash!==actual){fs.unlinkSync(target);return res.status(400).json({success:false,message:"SHA-256 verification failed"})}const file=await File.create({name:s.fileName,originalName:s.fileName,extension:ext(s.fileName),mimeType:s.mimeType,size:s.size,hash:actual,owner:req.user._id,folder:s.folder,storagePath:target});req.user.usedStorage+=s.size;await req.user.save();s.status="complete";await s.save();fs.rmSync(s.tempDir,{recursive:true,force:true});ok(res,{file},"Resumable upload complete")}catch(e){next(e)}});
router.get("/admin/stats",admin,async(req,res,next)=>{try{const [users,files,shared,deleted,agg]=await Promise.all([User.countDocuments(),File.countDocuments({trashed:false}),Share.countDocuments(),File.countDocuments({trashed:true}),File.aggregate([{$match:{trashed:false}},{$group:{_id:null,size:{$sum:"$size"}}})]);ok(res,{totalUsers:users,totalFiles:files,totalStorageUsed:agg[0]?.size||0,sharedFiles:shared,deletedFiles:deleted})}catch(e){next(e)}});
router.get("/admin/users",admin,async(req,res,next)=>{try{ok(res,{users:await User.find().select("-passwordHash").sort({createdAt:-1})})}catch(e){next(e)}});
router.patch("/admin/users/:id",admin,async(req,res,next)=>{try{const u=await User.findById(req.params.id);if(!u)return res.status(404).json({success:false,message:"User not found"});if("disabled"in req.body)u.disabled=!!req.body.disabled;if("quota"in req.body)u.quota=Number(req.body.quota);await u.save();ok(res,{user:u},"User updated")}catch(e){next(e)}});
router.get("/folders/:id/zip",async(req,res,next)=>{try{const folder=await Folder.findOne({_id:req.params.id,owner:req.user._id,trashed:false});if(!folder)return res.status(404).json({success:false,message:"Folder not found"});res.attachment(`${folder.name}.zip`);const archive=archiver("zip",{zlib:{level:9}});archive.on("error",next);archive.pipe(res);const files=await File.find({owner:req.user._id,folder:folder._id,trashed:false});for(const f of files){if(fs.existsSync(f.storagePath))archive.file(f.storagePath,{name:f.name})}await archive.finalize();}catch(e){next(e)}});
module.exports=router;
